LiveChartGallery/Models/ChartModel.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace LiveChartGallery.Models
{
    public class ChartModel
    {
        public string chartType { get; set; }
        public string chartSubType { get; set; }
        public string FilePath { get; set; }
        public string HtmlTable { get; set; }
        public DataTable dataTable { get; set; }
        public GenericAmchart genericAmchart { get; set; }
    }
}

LiveChartGallery/Models/Dashboard.cs
using MvcContrib.Pagination;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LiveChartGallery.Models
{
    public class Dashboard
    {
        public Dashboard() {
            lstDashboard = new List<Dashboard>();
          
        }
        public int Id { get; set; }

        public String Name { get; set; }

        public int Widgets_No { get; set; }

        public List<Dashboard> lstDashboard { get; set; }
        public int WidgetId { get; set; }
        public string Title { get; set; }
        public string EmbeddedUrl { get; set; }
        public string WidgetValue { get; set; }

        public string Widgetstatus { get; set; }
        public List<SelectListItem> Charturls { get; set; }

       public IPagination<Dashboard> DashboardResults { get; set; }



        public int SaveDashboard(Dashboard dashboard,int userProfileId )
        {
            string connection = ConfigurationManager.ConnectionStrings["connChartGallry"].ToString();
            int result = 0;
            using (SqlConnection scon = new SqlConnection(connection))
            {
                SqlCommand cmd = new SqlCommand("SaveDashboard", scon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add(new SqlParameter("@Name", dashboard.Name));
                cmd.Parameters.Add(new SqlParameter("@WidgetNo", dashboard.Widgets_No));
                cmd.Parameters.Add(new SqlParameter("@UserProfileId", userProfileId));
                scon.Open();
                result = cmd.ExecuteNonQuery();
            }
            return result;
        }


        public Dashboard GetAllDashboardById(int id)
        {
            string connection = ConfigurationManager.ConnectionStrings["connChartGallry"].ToString();
            //DataTable dt = new DataTable();
            Dashboard dashboard = new Dashboard();
            using (SqlConnection scon = new SqlConnection(connection))
            {
                SqlCommand cmd = new SqlCommand("GetDashboardById", scon);
                cmd.Parameters.Add(new SqlParameter("@Id", id));
                cmd.CommandType = CommandType.StoredProcedure;
                scon.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.HasRows)
                    while (dr.Read())
                    {
                        dashboard.Id = (int)dr["Id"];
                        dashboard.Name = dr["Name"].ToString();
                        dashboard.Widgets_No = (int)dr["WidgetNo"];
                    }
                return dashboard;
            }
        }

        public Dashboard    GetWidgetById(int wid)
        {
            string connection = ConfigurationManager.ConnectionStrings["connChartGallry"].ToString();
            //DataTable dt = new DataTable();
            Dashboard dashboard = new Dashboard();
            using (SqlConnection scon = new SqlConnection(connection))
            {
                SqlCommand cmd = new SqlCommand("GetWidgetById", scon);
                cmd.Parameters.Add(new SqlParameter("@WId", wid));
                cmd.CommandType = CommandType.StoredProcedure;
                scon.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.HasRows)
                    while (dr.Read())
                    {
                        dashboard.WidgetId = (int)dr["widgetid"];
                        dashboard.Title = dr["Title"].ToString();
                        dashboard.EmbeddedUrl = dr["EmbeddedUrl"].ToString();
                        dashboard.Id = (int)dr["Dashboardid"];
                    }
                return dashboard;
            }
        }
        public List<Dashboard> GetAllWidgetsbyDashboardId(int id)
        {
            string connection = ConfigurationManager.ConnectionStrings["connChartGallry"].ToString();
            //DataTable dt = new DataTable();
            List<Dashboard> lstdashboard = new List<Dashboard>();
 
  
            using (SqlConnection scon = new SqlConnection(connection))
            {
                SqlCommand cmd = new SqlCommand("GetAllWidgetsBYDashboardId", scon);
                cmd.Parameters.Add(new SqlParameter("@Id", id));
                cmd.CommandType = CommandType.StoredProcedure;
                scon.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.HasRows)
                    while (dr.Read())
                    {
                        var dashboard = new Dashboard();
                        dashboard.Id = (int)dr["Id"];
                        dashboard.Name = dr["Name"].ToString();
                        dashboard.Widgets_No = (int)dr["WidgetNo"];
                        dashboard.WidgetId = (int)dr["widgetid"];
                        dashboard.Title =Convert.ToString(dr["Title"]);
                        dashboard.EmbeddedUrl = Convert.ToString(dr["EmbeddedUrl"]);
                        dashboard.WidgetValue = Convert.ToString(dr["WidgetValue"]);
                        dashboard.Widgetstatus = Convert.ToString(dr["Widgetstatus"]);
                        lstdashboard.Add(dashboard);

                    }
                return lstdashboard;
            }
        }

        public List<Dashboard> GetAllDashboard(int userprofileId)
        {
            string connection = ConfigurationManager.ConnectionStrings["connChartGallry"].ToString();
            DataTable dt = new DataTable();
            Dashboard dashboard = new Dashboard();
            using (SqlConnection scon = new SqlConnection(connection))
            {
                SqlCommand cmd = new SqlCommand("GetDashboard", scon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add(new SqlParameter("@UserProfileId", userprofileId));
                scon.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.HasRows)
                    while (dr.Read()) {
                        var temp = new Dashboard();
                        temp.Id = (int)dr["Id"];
                        temp.Name = dr["Name"].ToString();
                        temp.Widgets_No = (int)dr["WidgetNo"];
                        dashboard.lstDashboard.Add(temp);
                    }
                return dashboard.lstDashboard;
            }
        }

        public int UpdateDashboard(Dashboard dashboard)
        {
            string connection = ConfigurationManager.ConnectionStrings["connChartGallry"].ToString();
            //Dashboard dashboard = new Dashboard();
            int result=0;
            using (SqlConnection scon = new SqlConnection(connection))
            {
                using (SqlCommand cmd = new SqlCommand("UpdateDashboard", scon)) {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add(new SqlParameter("@Id", dashboard.Id));
                    cmd.Parameters.Add(new SqlParameter("@Name", dashboard.Name));
                    cmd.Parameters.Add(new SqlParameter("@WidgetNo", dashboard.Widgets_No));
                    scon.Open();
                    result= cmd.ExecuteNonQuery();
                }
            }
            return result;
        }

        public int UpdateWidgetsbyId(Dashboard dashboard)
        {
            string connection = ConfigurationManager.ConnectionStrings["connChartGallry"].ToString();
            //Dashboard dashboard = new Dashboard();
            int result =0;
            using (SqlConnection scon = new SqlConnection(connection))
            {
                using (SqlCommand cmd = new SqlCommand("UpdateWidgetBYId", scon))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add(new SqlParameter("@widgetid", dashboard.WidgetId));
                    cmd.Parameters.Add(new SqlParameter("@Title", dashboard.Title));
                    cmd.Parameters.Add(new SqlParameter("@EmbeddedUrl", dashboard.EmbeddedUrl));
                    scon.Open();
                    result = cmd.ExecuteNonQuery();
                }
            }
            return result;
        }

        public int DeleteDashboard(int id) {
            int result = 0;
            string connection = ConfigurationManager.ConnectionStrings["connChartGallry"].ToString();
            using (SqlConnection scon = new SqlConnection(connection))
            {
                using (SqlCommand cmd = new SqlCommand("DeleteDashboard", scon))
                {
                    cmd.Parameters.Add(new SqlParameter("@Id", id));
                    cmd.CommandType = CommandType.StoredProcedure;
                    scon.Open();
                    result = cmd.ExecuteNonQuery();
                }
            }
            return result;

        }
    }
  
}

LiveChartGallery/Controllers/DashboardController.cs
using LiveChartGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using MvcContrib.Pagination;

namespace LiveChartGallery.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public int result = 0;
        // GET: Dashboard
        public ActionResult Index(QueryContextRequestDetails queryContext)
        {

            int userprofileid = 0;
            if (Session != null)
            {
                userprofileid = Convert.ToInt32(Session["UserID"]);
            }
            if ( userprofileid > 0)
            {

                Dashboard dashboard = new Dashboard();
                //  int UserprofileId = Convert.ToInt32(Session["UserID"].ToString());

                var lstDashboard = dashboard.GetAllDashboard(userprofileid);


                queryContext.RecordCount = lstDashboard.Count();
                queryContext.RecordsPerPage = queryContext.PageSize == 0 ? 10 : queryContext.PageSize;
                queryContext.PageNumber = queryContext.PageNumber == 0 ? 1 : queryContext.PageNumber;

                int? pagenumebr;
                pagenumebr = queryContext.PageNumber;

                IEnumerable<Dashboard> Idashboard = lstDashboard.ToPagedList(pagenumebr ?? 1, queryContext.RecordsPerPage);

                var viewModel = new Dashboard();

                viewModel.Id = queryContext.Id;
                viewModel.DashboardResults = new CustomPagination<Dashboard>(Idashboard, queryContext.PageNumber, queryContext.RecordsPerPage, (int)queryContext.RecordCount);
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
         
        }
        [HttpGet]
        public ActionResult CreateDashboard()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateDashboard(Dashboard dashboard)
        {
            int UserprofileId = Convert.ToInt32(Session["UserID"].ToString());
            if (dashboard.Id==0)
             result =dashboard.SaveDashboard(dashboard, UserprofileId);
            if (result > 0)
            {
                ViewBag.Result = result;
                ViewBag.Msg = "DashBoard Created.";
                return RedirectToAction("Index");
            }
            else
                return View();
        }
        [HttpGet]
        public ActionResult EditDashboard(int Id)
        {
            Dashboard dashboard = new Dashboard();
            if (Id > 0)
                dashboard= dashboard.GetAllDashboardById(Id);
            return View(dashboard);
        }
        [HttpPost]
        public ActionResult EditDashboard(Dashboard dashboard)
        {
            //int result = 0;
            if (dashboard.Id > 0)
            {
                result = dashboard.UpdateDashboard(dashboard);
            }
            if (result > 0) { 
                ViewBag.Result = result;
            ViewBag.Msg = "DashBoard Updated.";
            }
            return RedirectToAction("Index");
        }
        public ActionResult DeleteDashboard(int Id)
        {
            Dashboard dashboard = new Dashboard();
            if (Id > 0) {
               result= dashboard.DeleteDashboard(Id);
            }
            if (result > 0) {
                ViewBag.Result = result;
                ViewBag.Msg = "DashBoard Deleted.";
            }
            return RedirectToAction("Index");
        }
        public ActionResult PreViewDashboard(int Id)
        {
            List<Dashboard> dashboard = new List<Dashboard>();
            Dashboard objDashboard = new Dashboard();
            if (Id > 0)
                dashboard = objDashboard.GetAllWidgetsbyDashboardId(Id);

          
            return View(dashboard);
        }
        public class QueryContextRequestDetails
        {
            public int Id { get; set; }
            public int RecordsPerPage { get; set; }
            public int PageNumber { get; set; }

            public int PageSize { get; set; }

            public int RecordCount { get; set; }
        }
        public ActionResult DashboardPreview(int Id)
        {
            List<Dashboard> dashboard = new List<Dashboard>();
            Dashboard objDashboard = new Dashboard();
            if (Id > 0)
                dashboard = objDashboard.GetAllWidgetsbyDashboardId(Id);
                      
            return View(dashboard);
           
        }
        public ActionResult Details(int WId)
        {
            Dashboard widgetdata = new Dashboard();
            if (WId > 0)
                widgetdata = widgetdata.GetWidgetById(WId);
            GenericAmchart genericAmchart = new GenericAmchart();
            List<SelectListItem> chrturls = new List<SelectListItem>();
            int userprofileid = 0;
            if (Session != null)
            {

                userprofileid = Convert.ToInt32(Session["UserID"]);
           
            }
            var lstcharts = genericAmchart.GetChatsDetails(userprofileid);
            foreach (var item in lstcharts)
            {
                var temp = new SelectListItem
                {
                    Value = item.embedText,
                    Text = item.ChartTitle
                };
                chrturls.Add(temp);
            }
            ViewBag.Charturls = chrturls;

            return PartialView("_Chartmodel", widgetdata);
        }
        [HttpPost]
        public ActionResult Details(Dashboard dashboard)
        {
            //int result = 0;
            if (dashboard.Id > 0)
            {
                result = dashboard.UpdateWidgetsbyId(dashboard);
            }

            return Json(new { result = result });

        }

    }
}

LiveChartGallery/Views/Dashboard/CreateDashboard.cshtml
@model LiveChartGallery.Models.Dashboard

@{
    ViewBag.Title = "Create Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    if (@ViewBag.Result > 0) {
        alert("Dashboard Created");
    }
    else{
        alert("Error!!!");
    }
</script>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="main-content">
        <div class="grid-container">
            <div class="grid-x grid-margin-x grid-margin-y">
                <div class="cell">
                    <button type="button" class="button back" onclick="location.href='@Url.Action("index", "Dashboard")'">Back to List</button>
                    <div class="grid-x align-bottom">
                        <div class="cell medium-auto h-group">
                            <h1 class="regular">Create dashboard </h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("NAME", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>  

        <div class="form-group">
            @Html.Label("NUMBER OF WIDGETS ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> lstSelected = new List<SelectListItem>();
                    lstSelected.Add(new SelectListItem()
                    {
                        Text = "Select"
                    });
                    for (int i = 1; i <=4; i++)
                    {
                        lstSelected.Add(new SelectListItem()
                        {
                            Text = (i * 3).ToString(),
                            Value = (i * 3).ToString()
                        });
                    }
                }
                @Html.DropDownList("Widgets_No",lstSelected, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Widgets_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="beta secondary button" />
            </div>
        </div>
    </div>
}

LiveChartGallery/Views/Dashboard/DashboardPreview.cshtml
@model IEnumerable<LiveChartGallery.Models.Dashboard>
@{
    ViewBag.Title = "Preview Dashboard";
}
<script src="~/Scripts/gdpagination.js"></script>
@*<div>*@
@*<button class="beta secondary button" onclick="location.href='@Url.Action("Index", "Dashboard")'">Back to List</button>*@
@*@Html.ActionLink("Back to List", "Index")*@
@*</div>*@
@foreach (var item in Model)
{
    ViewBag.Name = item.Name;
    if (item.Name != null)
    {
        break;
    }

}
<div class="main-content">
    <div class="grid-container">
        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell">
                <div class="grid-x align-bottom">
                    <div class="cell medium-auto h-group">
                        <h1 class="regular">@ViewBag.Name</h1> <h1 class="regular">Preview Dashboard</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="cell">

    
        <div class="grid-x grid-margin-x grid-margin-y">
            
            @foreach (var item in Model)
    {

    <div class="cell medium-6">
        <div class="module gutter-collapse" style="background-color:#fff;">
            <!--module 004-->

            <div class="grid-x grid-margin-x grid-margin-y">
                <div class="cell">

                    <div class="grid-x graph-chart">

                        <div style="padding: 5px 12px 0px;background-color: #fff;width: 100%;min-height:40px;">
                            <h6 class="medium" style="font-weight: 400;display:inline-table;max-width:76%">@item.Title</h6>
                            @*<a href="#chapter4" style="float:right">Edit</a>*@
                        </div>
                        @*<div style="padding: 5px 12px 0px;background-color: #fff;width: 100%;min-height:45px;">
                                <h6 class="medium" style="font-weight: 400;display:inline-table;max-width:76%;word-break: break-all;">@item.EmbeddedUrl</h6>
                            </div>*@

                        <div class="cell chart" id="div1">
                            <iframe src='@item.EmbeddedUrl' frameborder='0' scrolling='no' style='width:100%;height:420px;'></iframe>


                        </div>

                    </div>
                    <div style="text-align:center">
                        @*<h6 style="text-align: center;display:inline-block;">DashBoard Count:</h6><span></span>*@
                    </div>



                </div>
                <!-- End of graph chart -->
            </div>
        </div>

    </div>
    }


        </div>


     

    </div>

</div>

LiveChartGallery/Views/Dashboard/EditDashboard.cshtml
@model LiveChartGallery.Models.Dashboard

@{
    ViewBag.Title = "EditDashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="main-content">
        <div class="grid-container">
            <div class="grid-x grid-margin-x grid-margin-y">
                <div class="cell">
                    <button type="button" class="button back" onclick="location.href='@Url.Action("index", "Dashboard")'">Back to List</button>
                    <div class="grid-x align-bottom">
                        <div class="cell medium-auto h-group">
                            <h1 class="regular">@Model.Name</h1>  <h1 class="regular">Edit Dashboard</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Widgets_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> lstSelected = new List<SelectListItem>();
                    lstSelected.Add(new SelectListItem()
                    {
                        Text = "Select"
                    });
                    for (int i = 1; i <= 4; i++)
                    {
                        lstSelected.Add(new SelectListItem()
                        {
                            Text = (i * 2).ToString(),
                            Value = (i * 2).ToString()
                        });
                    }
                }
                @Html.DropDownList("Number of Widget", lstSelected, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Widgets_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="beta secondary button" />
            </div>
        </div>
    </div>
}

LiveChartGallery/Views/Dashboard/PreViewDashboard.cshtml
@model IEnumerable<LiveChartGallery.Models.Dashboard>
@{
    ViewBag.Title = "Preview Dashboard";
}

@foreach (var item in Model)
{
    ViewBag.Name = item.Name;
    if (item.Name!=null)
    {
        break;
    }

}

<script src="~/Scripts/gdpagination.js"></script>
<div class="main-content">
    <div class="grid-container">
        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell">
                <button type="button" class="button back" onclick="location.href='@Url.Action("index", "Dashboard")'">Back to List</button>
                <div class="grid-x align-bottom">
                    <div class="cell medium-auto h-group">
                        <h1 class="regular">@ViewBag.Name</h1>   <h1 class="regular">Edit Widgets</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="cell">
        

        <div class="grid-x grid-margin-x grid-margin-y">
            @*<input type="hidden" id="dashboardid" value="@Model.Id" />*@
        @foreach (var item in Model)
        {

        <div class="cell medium-6">
            <div class="module gutter-collapse" style="background-color:#fff;">
                <!--module 004-->

                <div class="grid-x grid-margin-x grid-margin-y">
                    <div class="cell">

                        <div class="grid-x graph-chart">

                            <div style="padding: 5px 12px 0px;background-color: #fff;width: 100%;min-height:40px;">
                                <h6 class="medium" style="font-weight: 400;display:inline-table;max-width:86%">@item.Title</h6>

                                <a href="#" id="btnShowModal" class="anchorDetail" data-id=@item.WidgetId style="font-weight: 400;float:right">
                                    <span>Edit</span>
                                </a>

                            </div>


                            <div class="cell chart" id="div1">
                                <iframe src='@item.EmbeddedUrl' frameborder='0' scrolling='no' style='width:100%;height:420px;'></iframe>


                            </div>

                        </div>



                    </div>
                    <!-- End of graph chart -->
                </div>
            </div>

        </div>

        }


        </div>


        

        @*@Html.PagedListPager(Model, page => Url.Action("PreViewDashboard", new { page, Id = Model.First().Id }))*@


        </div>

    </div>

        <div id='myModal' class='modal'>
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div id='myModalContent'></div>
                </div>

            </div>

        </div>

        <script>


            var TeamDetailPostBackURL = '/Home/Details';
            $(function () {
                $(".anchorDetail").click(function () {
                    debugger;
                    var $buttonClicked = $(this);
                    var id = $buttonClicked.attr('data-id');
                    var options = { "backdrop": "static", keyboard: true };
                    $.ajax({
                        type: "GET",
                        url: '/Dashboard/Details',
                        contentType: "application/json; charset=utf-8",
                        data: { "WId": id },
                        datatype: "json",
                        success: function (data) {
                            debugger;
                            $('#myModalContent').html(data);
                            $('#myModal').modal(options);
                            $('#myModal').modal('show');

                        },
                        error: function () {
                            alert("Dynamic content load failed.");
                        }
                    });
                });
                //$("#closebtn").on('click',function(){
                //    $('#myModal').modal('hide');

                $("#closbtn").click(function () {
                    $('#myModal').modal('hide');
                });
            });

        </script>

LiveChartGallery/Views/Dashboard/_Chartmodel.cshtml
@model LiveChartGallery.Models.Dashboard

<div class="modal-header">
   Chart details 
  
        <button type="button" class="close" data-dismiss="modal">&times;</button>


</div>

<div class="container">
  
    <div class="row" style="margin-top: 12px;">
        <div class="col-md-2">
        Title
        </div>
        <div  class="col-md-10">
            <input type="text" id="Title" value='@Model.Title' />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            Select Chart
        </div>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Name, (IEnumerable<SelectListItem>)ViewBag.Charturls, "Select", new { id = "charturl" })
        </div>
    </div>
  
  

   <input type="hidden" id="Id" value='@Model.Id' />
    <input type="hidden" id="WidgetId" value='@Model.WidgetId' />
</div>
<div style="text-align:right;margin-right:10px;padding:6px;">
    <input type="submit" id="btnmodelupdate" value="Update" class="beta secondary button" />

</div>


<script>
    $(function () {
        
        
        $("#btnmodelupdate").click(function () {
            
            $.ajax({
                type: 'POST',
                url: '/Dashboard/Details',
                data: {
                    WidgetId: $('#WidgetId').val(),
                    Title: $('#Title').val(),
                    EmbeddedUrl: $('#charturl').val(),
                    value: $('#WidgetValue').val(),
                    Id: $('#Id').val()
                },
               
                success: function (data) {
                 
                    location.reload(true);
                    $('#myModal').modal('hide');
                //  window.location.href = window.location.href;
                   // window.location.reload();
                    //window.top.location.reload();
                }

            });
        });
    });
</script>